-- Actualizar especificaciones de 5 productos
-- Ejecutar en Supabase SQL Editor

UPDATE products SET 
    name = 'Mesa Plegable 1.80 × 70',
    description = E'TAMAÑO: L180*W70*H74CM\nMATERIAL: HDPE + ACERO\nMARCO DE ACERO: DIA 22*1.0 MM\nEMPAQUE: BOLSA DE PE POR PIEZA Y CAJA DE CARTÓN\nTAMAÑO CAJA: 90*71*8 CMS\nPESO: 11 KGS\nCANT POR TARIMA: 40 PIEZAS'
WHERE sku = 'GL09';

UPDATE products SET 
    name = 'Toldo Plegable 3×4.5 (Automático)',
    description = E'TAMAÑO: 3 X 4.5 MTS\nMATERIAL: ACERO CON RECUBRIMIENTO BLANCO\nTELA: POLIÉSTER 800D CON RECUBRIMIENTO PVC (IMPERMEABLE)\nTUBO EXTERIOR DEL PIE: 30 X 30 X 0.7 MM\nTUBO INTERIOR DEL PIE: 25 X 25 X 0.7 MM\nTUBO TRANSVERSAL: 13 X 23 X 0.7 MM\nCONECTORES: PLÁSTICO ABS DE ALTA RESISTENCIA\nADICIONALES: BOTÓN DE SEGURIDAD ANTI-PELLIZCOS\nBASE DE PIE SILENCIOSA\nINCLUYE MANUAL DE INSTRUCCIONES\nEMPAQUE: TECHO + ESTRUCTURA EN BOLSA DE PE POR PIEZA Y CAJA DE CARTÓN\nTAMAÑO CAJA: 156*30*22 CMS\nPESO: 23.8 KGS\nCANT POR TARIMA: 24 PIEZAS'
WHERE sku = 'GL12';

UPDATE products SET 
    name = 'Toldo Plegable 3×6 (Automático)',
    description = E'TAMAÑO: 3 X 6 MTS\nMATERIAL: ACERO CON RECUBRIMIENTO BLANCO\nTELA: POLIÉSTER 800D CON RECUBRIMIENTO PVC (IMPERMEABLE)\nTUBO EXTERIOR DEL PIE: 30 X 30 X 0.7 MM\nTUBO INTERIOR DEL PIE: 25 X 25 X 0.7 MM\nTUBO TRANSVERSAL: 13 X 23 X 0.7 MM\nCONECTORES: PLÁSTICO ABS DE ALTA RESISTENCIA\nADICIONALES: BOTÓN DE SEGURIDAD ANTI-PELLIZCOS\nBASE DE PIE SILENCIOSA\nINCLUYE MANUAL DE INSTRUCCIONES\nEMPAQUE: TECHO + ESTRUCTURA EN BOLSA DE PE POR PIEZA Y CAJA DE CARTÓN\nTAMAÑO CAJA: 156*39*24 CMS\nPESO: 32.9 KGS\nCANT POR TARIMA: 18 PIEZAS'
WHERE sku = 'GL13';

UPDATE products SET 
    name = 'Silla Plegable C17',
    description = E'TAMAÑO: L49*W45*H84 CMS\nMATERIAL: HDPE + ACERO\nMARCO DE ACERO: DIA 22*1.0 MM\nEMPAQUE: BOLSA DE PE POR PIEZA, 6 PIEZAS POR CAJA\nTAMAÑO CAJA: 111*32*46 CMS\nPESO: 4.3 KGS\nCANT POR TARIMA: 96 PIEZAS'
WHERE sku = 'GL22';

UPDATE products SET 
    name = 'Silla Plegable C17 Black',
    description = E'TAMAÑO: L49*W45*H84 CMS\nMATERIAL: HDPE + ACERO\nMARCO DE ACERO: DIA 22*1.0 MM\nEMPAQUE: BOLSA DE PE POR PIEZA, 6 PIEZAS POR CAJA\nTAMAÑO CAJA: 111*32*46 CMS\nPESO: 4.3 KGS\nCANT POR TARIMA: 96 PIEZAS'
WHERE sku = 'GL23';
